### ISSUE TITLE
Generalize the Touch gesture

### ISSUE THREAD

**Issue by samamou** [Puara/puara-gestures#19]
`multiRub` and `multiBrush` are [currently initialized](https://github.com/Puara/puara-gestures/blob/33441a5992bcc8c30305a8d3906c85afba5124fa/include/puara/descriptors/touch.h#L19) as fixed-sized array of [4], the logic can be updated to support dynamic arrays.

- [ ] generalize gestures like **rub** and **brush** (1 DoF) 
- [ ] update Touch class to support dynamic arrays?

**Comment by edumeneses** [comment]
Isn't this a duplicate of #16 ?

**Comment by samamou** [comment]
> Isn't this a duplicate of #16 ?

oops - just added to the other description and will delete this @edumeneses
